#!/usr/bin/env bash
# =============================================================================
# scripts/dump_functions.sh  (workstream B4 — capture live functions)
# =============================================================================
# Purpose:
#   Several SECURITY DEFINER functions referenced by application code are NOT in
#   version control (e.g. _elan_membership_covers, _elan_add_ledger,
#   elan_credit_balance, booking_eligibility_self, book_class_self,
#   mark_no_show, checkin_by_code). This script captures the CURRENT definitions
#   of all functions in the "public" schema from a live/staging database into a
#   migration stub so they can be reviewed, renumbered, and committed.
#
# What it does:
#   * Dumps public-schema function definitions to:
#       supabase/migrations/0099_captured_live_functions.sql
#   * Prepends operator instructions (renumber/split, run verify_rls.sql).
#   * Performs NO destructive action. It only READS from the DB and WRITES one
#     new file inside the repo.
#
# Usage:
#   DB_URL="postgresql://user:pass@host:5432/dbname" ./scripts/dump_functions.sh
#
# SAFETY:
#   Apply to STAGING first. Never run an untested capture against production.
# =============================================================================

set -euo pipefail

# --- Resolve repo paths (script lives in <repo>/scripts) ---------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_FILE="${REPO_ROOT}/supabase/migrations/0099_captured_live_functions.sql"

# --- Require DB_URL ----------------------------------------------------------
if [[ -z "${DB_URL:-}" ]]; then
    cat >&2 <<'USAGE'
ERROR: DB_URL is not set.

Usage:
    DB_URL="postgresql://user:pass@host:5432/dbname" ./scripts/dump_functions.sh

DB_URL must point at the database whose public-schema functions you want to
capture. Use a STAGING connection string first.
USAGE
    exit 1
fi

# --- Loud safety reminder ----------------------------------------------------
echo "==================================================================="
echo "B4 FUNCTION CAPTURE"
echo "Apply to STAGING first. Never run an untested capture against production."
echo "Target output: ${OUT_FILE}"
echo "==================================================================="

mkdir -p "$(dirname "${OUT_FILE}")"

# --- Header written into the captured migration ------------------------------
# Written first; the dump is appended below.
cat > "${OUT_FILE}" <<'HEADER'
-- =============================================================================
-- 0099_captured_live_functions.sql  (AUTO-CAPTURED — NOT READY TO APPLY AS-IS)
-- =============================================================================
-- This file was generated by scripts/dump_functions.sh from a LIVE database.
-- It contains the public-schema function definitions that were missing from
-- version control (B4 capture).
--
-- OPERATOR TODO before committing / applying:
--   1. RENUMBER: 0099 is a placeholder. Move/rename to the correct sequential
--      migration number for this branch so it applies in the right order.
--   2. SPLIT: Consider splitting unrelated functions into separate, focused
--      migrations (e.g. payments, booking, check-in) for reviewability.
--   3. REVIEW each function: confirm SECURITY DEFINER vs INVOKER, search_path
--      pinning, and EXECUTE grants (anon/authenticated must NOT execute
--      payment/fulfillment functions).
--   4. After loading into staging, run:  psql "$DB_URL" -f scripts/verify_rls.sql
--      and resolve every GAP / FAILURE it reports.
--
-- DO NOT treat this file as verified. It is a starting point only.
-- =============================================================================

HEADER

# --- Perform the capture -----------------------------------------------------
# Prefer the Supabase CLI; fall back to pg_dump. Both are READ-ONLY operations.
# We dump only the "public" schema and keep schema-only (no data).
echo "Capturing public-schema function definitions..."

if command -v supabase >/dev/null 2>&1; then
    echo "Using: supabase db dump"
    # --schema public limits scope; output appended to the header file.
    supabase db dump --db-url "${DB_URL}" --schema public >> "${OUT_FILE}"
elif command -v pg_dump >/dev/null 2>&1; then
    echo "Using: pg_dump (fallback)"
    # -s = schema only (no data), -n public = public schema only.
    # This emits all public objects including functions; the operator should
    # trim non-function objects when splitting per the header TODO.
    pg_dump --schema-only --schema=public "${DB_URL}" >> "${OUT_FILE}"
else
    echo "ERROR: neither 'supabase' nor 'pg_dump' found on PATH." >&2
    echo "Install the Supabase CLI or PostgreSQL client tools and retry." >&2
    exit 1
fi

# --- Done --------------------------------------------------------------------
echo "==================================================================="
echo "Capture written to: ${OUT_FILE}"
echo "NEXT STEPS:"
echo "  1. Renumber / split the migration per the header TODO."
echo "  2. Run:  psql \"\$DB_URL\" -f scripts/verify_rls.sql"
echo "  3. Resolve every GAP / FAILURE before applying to production."
echo "Reminder: Apply to STAGING first. Never run an untested capture against production."
echo "==================================================================="
